---
spring:
  profiles: default
  datasource:
    url: "jdbc:sqlite:C:\\Users\\diona\\Documents\\Bachelorproef repo\\products-service\\sqlite.db"
    driver-class-name: org.sqlite.JDBC
    initialization-mode: never
    hikari:
      maximum-pool-size: 1